### ISSUE TITLE
Encountered an JSON error on repeated running of the code

### ISSUE THREAD

**Issue by AbhishekVarghese** [mubaris/motivate#80]
None of the originals files were changed to add this feature. My python file is only using subprocess.popen("motivate") to run this, and this happened while I was repeatedly testing it.

![screenshot from 2017-11-29 13-10-04](https://user-images.githubusercontent.com/22749216/33363864-26b2766c-d508-11e7-8f16-f9e34fd12a3f.png)

**Comment by mubaris** [comment]
I think this due to some JSON error in one of the JSON files. Try running the same one or more time. If it's repeating, we will figure out something

**Comment by AbhishekVarghese** [comment]
Ya it does repeat if we run the command repeatedly

**Comment by AbhishekVarghese** [comment]
I am attatching another screenshot where I am doing this explicitly without help of my code. There is certain data perhaps that is not proerly formatted and hence this error is sent whenever it picks up the data.

You also try this in your machine. Run this command repeatedly. If you do it ample no. of times this error will indeed pop up.

![screenshot from 2017-11-29 17-49-14](https://user-images.githubusercontent.com/22749216/33375133-f475b5a2-d52e-11e7-83e5-d31be2113bdf.png)

**Comment by lyupin** [comment]
One reason is some json files like 104.json used capitalized key "Quote" instead of "quote". So you will see KeyError. It has been fixed in Merge request #104 . That fix will also automatically do correction for the problematic json file.
Another JSON decoder error is caused because there is a redundant comma after last group of quote, for example, the last several lines in 120.json:
`
{
      "author": "Jack Ma",
      "quote": "No matter how tough the chase is, you should always have the dream you saw on the first day. It’ll keep you motivated and rescue you (from any weak thoughts)."
    },

  ]
}
`
Delete the comma, it runs smoothly.
`
{
      "author": "Jack Ma",
      "quote": "No matter how tough the chase is, you should always have the dream you saw on the first day. It’ll keep you motivated and rescue you (from any weak thoughts)."
    }

  ]
}
